export type SteamSpyGameData = {
  appid: number;
  name: string;
  developer: string;
  publisher: string;
  score_rank: string;
  positive: number;
  negative: number;
  userscore: number;
  owners: string;
  average_forever: number;
  average_2weeks: number;
  median_forever: number;
  median_2weeks: number;
  price: number | null;
  initialprice: number | null;
  discount: number | null;
  ccu: number;
  languages: string | null;
  genre: string;
  tags: string[];
};
